services:
  backend:
    build:
      context: ./complete/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./complete/backend:/app
    environment:
      - DATABASE_URL=sqlite:///threads_app.db
    restart: unless-stopped

  frontend:
    build:
      context: ./complete/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://backend:8000

networks:
  default:
    driver: bridge
